import Monolithic102.Catalog

namespace Monolithic102.ME021

def spec : EquationSpec := catalog[20]!

/- Canonical source expression:
Q = −(ħ²/2m)(∇²ρ/ρ)

Descriptor:
Nonclassical potential generated by curvature in the amplitude field.
-/

end Monolithic102.ME021
